name: "action-setup-aws-sdk-client-go"
description: "Setup `fujiwara/aws-sdk-client-go`"
inputs:
  version:
    description: |
      aws-sdk-client-gen version specification.
      format: `vX.Y.Z` or `latest`
    required: false
    default: "latest"
  gen-yaml:
    description: |
      Relative path to gen.yaml from the repository root. 
      See: https://github.com/fujiwara/aws-sdk-client-go?tab=readme-ov-file#genyaml-configuration-file
    required: false
  client-go-gen:
    description: |
      It is set as the environment variable `AWS_SDK_CLIENT_GO_GEN`. 
      See: https://github.com/fujiwara/aws-sdk-client-go?tab=readme-ov-file#aws_sdk_client_go_gen-environment-variable
    required: false
runs:
  using: "composite"
  steps:
    - name: Find Go
      id: find-go
      run: |
        echo "find=$(type go > /dev/null 2>&1)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ">=1.21.0"
        cache: true
        cache-dependency-path: go.sum
      if: ${{ steps.find-go.outputs.find == 'false'}}

    - name: Checkout with version
      uses: actions/checkout@v4
      if: ${{ inputs.version != 'latest'}}
      with:
        repository: fujiwara/aws-sdk-client-go
        path: fujiwara/aws-sdk-client-go
        ref: ${{ inputs.version }}

    - name: Checkout
      uses: actions/checkout@v4
      if: ${{ inputs.version == 'latest'}}
      with:
        repository: fujiwara/aws-sdk-client-go
        path: fujiwara/aws-sdk-client-go
        fetch-depth: 0

    - name: Checkout latest version
      if: ${{ inputs.version == 'latest'}}
      run: |
        TAG=$(git describe --tags --abbrev=0)
        git checkout $TAG
      shell: bash
      working-directory: fujiwara/aws-sdk-client-go

    - name: Copy gen.yml
      run: cp ${{ inputs.gen-yaml }} ${{ github.workspace }}/fujiwara/aws-sdk-client-go/gen.yaml -f
      shell: bash
      if: ${{ inputs.gen-yaml }}

    - name: Build and Intall
      working-directory: fujiwara/aws-sdk-client-go
      env:
        AWS_SDK_CLIENT_GO_GEN: ${{ inputs.client-go-gen }}
      run: |
        go generate ./cmd/aws-sdk-client-gen .
        cd ./cmd/aws-sdk-client-go
        go install -installsuffix aws-sdk-client-go
        echo "$(go env GOPATH)/bin" >>"${GITHUB_PATH}"
      shell: bash

