name: "action-setup-awslim"
description: "Setup `fujiwara/awslim`"
branding:
  icon: cloud
  color: orange

inputs:
  awslim-version:
    description: |
      aws-sdk-client-gen version specification.
      format: `vX.Y.Z` or `latest`
    required: false
    default: "latest"
  gen-yaml-path:
    description: |
      Relative path to gen.yaml from the repository root. 
      See: https://github.com/fujiwara/awslim?tab=readme-ov-file#genyaml-configuration-file
    required: false
  awslim-gen:
    description: |
      It is set as the environment variable `AWSLIM_GEN`. 
      See: https://github.com/fujiwara/awslim?tab=readme-ov-file#awslim_gen-environment-variable
    required: false
  gen-yaml-inline:
    description: |
      Can be written gen.yaml with inline. 
      See: https://github.com/fujiwara/awslim?tab=readme-ov-file#genyaml-configuration-file
    required: false
runs:
  using: "composite"
  steps:
    - name: Check Go Version
      id: find-go
      continue-on-error: true
      run: |
        FOUND=$(type go > /dev/null 2>&1 && echo "true")
        echo ::set-output name=found::$FOUND
      shell: bash

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ">=1.21.0"
      if: ${{ steps.find-go.outputs.found != 'true'}}

    - name: Checkout with version
      uses: actions/checkout@v4
      if: ${{ inputs.awslim-version != 'latest'}}
      with:
        repository: fujiwara/awslim
        path: fujiwara/awslim
        ref: ${{ inputs.awslim-version }}

    - name: Checkout
      uses: actions/checkout@v4
      if: ${{ inputs.awslim-version == 'latest'}}
      with:
        repository: fujiwara/awslim
        path: fujiwara/awslim
        fetch-depth: 0

    - name: Checkout latest version
      if: ${{ inputs.awslim-version == 'latest'}}
      run: |
        TAG=$(git describe --tags --abbrev=0)
        git checkout $TAG
      shell: bash
      working-directory: fujiwara/awslim

    - name: Copy gen.yml
      run: cp ${{ inputs.gen-yaml-path }} ${{ github.workspace }}/fujiwara/awslim/gen.yaml -f
      shell: bash
      if: ${{ inputs.gen-yaml-path }}

    - name: Write gen.yml
      run: echo "${{ inputs.gen-yaml-inline }}" > ${{ github.workspace }}/fujiwara/awslim/gen.yaml
      shell: bash
      if: ${{ inputs.gen-yaml-inline }}

    - name: Build and Intall
      working-directory: fujiwara/awslim
      env:
        AWSLIM_GEN: ${{ inputs.awslim-gen }}
      run: |
        go generate ./cmd/awslim-gen .
        cd ./cmd/awslim
        go install -installsuffix awslim
      shell: bash

    - name: Export Path
      run: echo "$(go env GOPATH)/bin" >>"${GITHUB_PATH}"
      shell: bash

    - name: Export Path(PowerShell)
      if: ${{ runner.os == 'Windows'}}
      run: echo "$(go env GOPATH)\bin" >>"${GITHUB_PATH}"
      shell: pwsh