name: release

on:
  push:
    branches: [main]
    paths: ["CHANGELOG.md"]

permissions: write-all

jobs:
  test:
    uses: ./.github/workflows/ci.yaml

  release:
    needs:
      - test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Version
        id: versioning
        run: |
          VERSION="v$(sed -n 's/##\s\([0-9.]*\)\s.*/\1/p' CHANGELOG.md | head -1)"
          MAJOR_VERSION=$(echo $VERSION | cut -d. -f1)
          echo ::set-output name=version::$VERSION
          echo ::set-output name=major_version::$MAJOR_VERSION

      - name: Extract changes from prev version
        run: |
          PRETAG=$(git tag --sort -v:refname | head -1)
          CURRENTTAG=${{ steps.versioning.outputs.version }}
          echo "## What's Changed in ${CURRENTTAG}" > diff-changelog.txt
          if [ -z "$PRETAG" ]
          then
            cat CHANGELOG.md | grep -E '^\+' | grep -v '+++' | sed -e 's/^\+//g' | sed -e 's/##\s[0-9.]*\s.*//g' | sed -e '/^$/d' >> diff-changelog.txt
          else
            git diff $PRETAG..${{ github.sha }} -- CHANGELOG.md | grep -E '^\+' | grep -v '+++' | sed -e 's/^\+//g' | sed -e 's/##\s[0-9.]*\s.*//g' | sed -e '/^$/d' >> diff-changelog.txt
            echo "" >> diff-changelog.txt
            echo "**Full Changelog**: https://github.com/miyamo2/action-setup-awslim/compare/${PRETAG}...${CURRENTTAG}" >> diff-changelog.txt
          fi

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          generate_release_notes: false
          body_path: diff-changelog.txt

      - name: Push Alias tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.versioning.outputs.major_version }}